# Generated by Django 5.1.3 on 2024-11-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('on', 'Encendido'), ('off', 'Apagado'), ('paused', 'En Pausa'), ('operating', 'Operando')], max_length=50)),
                ('battery_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('start', 'Encender'), ('stop', 'Apagar'), ('pause', 'Pausar'), ('continue', 'Continuar')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='panel.mower')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='panel.mower')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obstacle_detected', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='panel.mower')),
            ],
        ),
    ]
